name: Run Weather Update Every 10 Minutes
on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"  # 厳密に10分ごと
  workflow_dispatch:

jobs:
  update_weather:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        env:
          API_TOKEN: ${{ secrets.HOCHU_API_TOKEN }} #これは自身の環境で生成して(openssl rand -hex 16).env.localの中に格納
        run: |
          curl -X GET "https://your-app.vercel.app/api/fetchWeather" \
            -H "Authorization: Bearer $API_TOKEN"